### ISSUE TITLE
[FEAT]: Update Convert Joints to Mesh so it does not include the parent joint of the selected joint when creating the resulting mesh.

### ISSUE THREAD

**Issue by RJJ** [TrevisanGMW/gt-tools#120]
### Description

Update GT Tools -> Utilities -> Convert Joints to Mesh so it does not include the parent joint of the selected joint when creating the resulting mesh.
    i.e. The current behavior: If you select the pelvis_jnt in the GT biped skeleton_grp and run Convert Joints to Mesh the created mesh includes a mesh representation of the selected joint, it's child joints AND it's parent joint(the root joint at 0,0,0 in this case).
         Desired behavior: It would be preferable NOT TO HAVE THE PARENT JOINT OF THE SELECTED JOINT INCLUDED when running Convert Joints to Mesh (i.e. only create the mesh from the selected joint and all it's child joints)

**Comment by TrevisanGMW** [comment]
Hi @RJJ,
Thanks for creating this issue and explaining the bug in detail. 🙌
I have already fixed it. The fix will be included in the next update.
In case you can't wait for the next version, feel free to grab the updated "convert_joints_to_mesh" function [here](https://github.com/TrevisanGMW/gt-tools/blob/dev-feature/tdd-pattern/utils/joint_utils.py).

**Comment by RJJ** [comment]
thank you!     On Sunday, July 16, 2023 at 11:49:33 AM PDT, Guilherme Trevisan ***@***.***> wrote:  
 
 


Closed #120 as completed.

**Comment by RJJ** [comment]
reinstalled manually and 3.4 is running.   thanks!
question.  Do you know if there is a way to make it possible to be able to see all the GUI text and also not have to scroll to see all the tabs for the windows in the screenshot by either-allowing them to be resizable or-autofit the window sizes fit the textor-make these default windows a little wider
and for any of the help windows that require scroll bars to see all of the help text at once, allow them to be resizable to it's possible to make them longer and wider to show more or all of the help text at once?


    On Monday, September 9, 2024 at 08:36:32 PM PDT, Guilherme Trevisan ***@***.***> wrote:  
 
 


Hey @RJJ, I've recently changed a few things in the import pattern. Could you try reinstalling it manually to see if it fixes it for you? You just have to download it latest release, unzip it, and drag and drop the script on your viewport.
I'm not planning to update the pattern again, so the updater should work fine after one manual reinstall.
