### ISSUE TITLE
Add option to Transfer Transforms for transferring pivots

### ISSUE THREAD

**Issue by RJJ** [TrevisanGMW/gt-tools#198]
### Description

Would be a helpful addition if the current transfer transforms tool also offered the option to transfer the pivots (rotate, scale and position) of each source object(s) pivot(s) to each target object(s) pivot(s)

**Comment by TrevisanGMW** [comment]
Hi @RJJ,
Thank you for the suggestion, I'll look into it!
Just to clarify, when you say pivot, do you mean update the pivot while keeping the object where it is, correct?
