### ISSUE TITLE
[BUG]: Traceback running Updater

### ISSUE THREAD

**Issue by RJJ** [TrevisanGMW/gt-tools#207]
### Description of the bug

Getting a traceback running Updater:
// Error: No module named 'gt.utils.setup_utils'
// # Traceback (most recent call last):
// #   File "/Users/rjj/Library/Preferences/Autodesk/maya/gt-tools/gt/tools/package_updater/package_updater_controller.py", line 198, in update_package
// #     self.model.update_package(cache=cache)
// #   File "/Users/rjj/Library/Preferences/Autodesk/maya/gt-tools/gt/tools/package_updater/package_updater_model.py", line 435, in update_package
// #     import gt.utils.setup_utils as setup_utils
// # ModuleNotFoundError: No module named 'gt.utils.setup_utils'

### Steps To Reproduce

run updater 

### Additional Information

running Maya 2024.1 Python 3.10

**Comment by GuilhermeTrevisan-Spliced** [comment]
Hey @RJJ, I've recently changed a few things in the import pattern. Could you try reinstalling it manually to see if it fixes it for you? You just have to download it latest release, unzip it, and drag and drop the script on your viewport.
I'm not planning to update the pattern again, so the updater should work fine after one manual reinstall.

**Comment by TrevisanGMW** [comment]
Hey @RJJ, I've recently changed a few things in the import pattern. Could you try reinstalling it manually to see if it fixes it for you? You just have to download it latest release, unzip it, and drag and drop the script on your viewport.
I'm not planning to update the pattern again, so the updater should work fine after one manual reinstall.

**Comment by RJJ** [comment]
reinstalled manually and it's working.
thanks!
