### ISSUE TITLE
[BUG]: Error:SyntaxError

### ISSUE THREAD

**Issue by Davinci-D7** [TrevisanGMW/gt-tools#208]
### Description of the bug

Hi! I cannot install gt-tools v3.4.0 in Maya 2022.4. I got an error after dragging the script into the viewport.
v3.3.1 is working fine.

![PixPin_2024-12-11_22-19-43](https://github.com/user-attachments/assets/c83c82ed-5b9e-4c79-800e-f52b0495de2a)

### Steps To Reproduce

1.Drag script into the viewport and check script editor.

**Comment by TrevisanGMW** [comment]
I've updated the tools ([v.3.4.1](https://github.com/TrevisanGMW/gt-tools/releases/tag/v3.4.1)) and removed the walrus operator causing the syntax error. Compatibility with Maya 2022 should be back now. 
Fix PR: #209

Feel free to re-open the PR in case you run into issues again.
