### ISSUE TITLE
Auto Bipped Rigger: lookdevKit plugin not loaded by default

### ISSUE THREAD

**Issue by charliewales** [TrevisanGMW/gt-tools#30]
Make sure lookdevKit plugin is loaded. I was getting errors when building.

# Warning: Unrecognized node type 'floatConstant'; preserving node information during this session. # 
# Warning: The source attribute 'left_leg_strechyInactive_value.outFloat' cannot be found.

I just added this to the gt_auto_biped_rigger.py:

```python
# Main Dialog ============================================================================
def build_gui_auto_biped_rig():
    '''  Creates the main GUI for GT Auto Biped Rigger '''

    if not cmds.pluginInfo("lookdevKit", query=True, loaded=True):
        cmds.loadPlugin("lookdevKit", quiet=True)
```

Thanks. Keep it up!

**Comment by TrevisanGMW** [comment]
Hey @charliewales,
Thank you very much for pointing that out! I've updated the script so it no longer uses "floatConstant" nodes.
