### ISSUE TITLE
Maya to Discord not working

### ISSUE THREAD

**Issue by ghost** [TrevisanGMW/gt-tools#54]
Error message: Error connecting to webhook. 

Tried different settings and servers, tried discord.com and discordapp.com, neither are working.

**Comment by TrevisanGMW** [comment]
Hey @j4cquesN
The only way I managed to replicate this error here was by getting my firewall to block Maya's internet connection.
When I try to use it with the firewall, I get the same error "Error connecting to webhook."
And the log gives me this error: "OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions".

Could you double check if for some reason your Maya's internet connection is limited? I'm using Netlimiter here for example, and I have to allow internet access to every request.

In case you're sure that the internet is available, but it's still not working, I added a print line for the error that is being raised. You can get this version from the "dev" branch:
https://github.com/TrevisanGMW/gt-tools/blob/dev/python-scripts/gt_maya_to_discord.py
This way, you can open the script editor and give me the full error it's returning.

My tests were done using Maya 2020.4 (Python 2) and Maya 2022 (Python 3)
You could also test your connection using "GT Tools > Help > Check for Updates" as it uses the same request methods.

Let me know how it goes :)

**Comment by ghost** [comment]
Thanks! It was blocked in my firewall.

Completely overlooked that sorry.
