### ISSUE TITLE
[FEAT]: Create tool to add/edit multiple custom attributes

### ISSUE THREAD

**Issue by TrevisanGMW** [TrevisanGMW/gt-tools#55]
Script would work exactly like the "Add attribute" function, but it would retain the parameters and allow for multiple variables (separated by commas)

**Comment by NovusEdge** [comment]
I'd like to take this issue up if it's still open

**Comment by TrevisanGMW** [comment]
> I'd like to take this issue up if it's still open

Hey @NovusEdge 
Yes, feel free to create it. Any help would be more than welcome.

To clarify the idea, here is a better description:
I thought of using a textField with a list of attributes the user could add to the selected objects. 
This textField would allow for multiple attributes to be added at the same time (these would be separated by commas)
Ideally the script would also have an option to delete all attributes in the list. (in case incorrectly created) 

Here are some other things we could add:
- The scalar options present in the “Add attribute” windows (so the user can customize what they want, such as datatype and minimum or maximum limits)
- A button to create a “separator” attribute (essentially a locked attribute with an enum containing dashes “-------” to be used as a separator)
- Maybe an import/export option?

Ideally the UI would be consistent with the rest of the scripts. So feel free to copy an existing script so you can to extract it from them.  "GT Path Manager" uses a QT version of it, while most of the other ones rely on Maya Cmds and the Open Maya library. "GT Generate Text Curve" has a similar system that uses a textfield to create curves, so it could be a good starting point.
If possible, try to keep all the code within the same script. I know it might be a bit inconvenient as it would be easier to create modules, but I'm trying to keep all scripts "standalone" in case people don't want to download the entire package.

Let me know in case you need any clarification or help :)

**Comment by TrevisanGMW** [comment]
Consider adding:
- Textfield with list of affected attributes.
- Hide/unhide attributes for selected elements.
- Lock/unlock attributes for selected elements.
- Auto create a list of attributes for selected elements.
- Auto delete a list of attributes for selected elements.
- Maybe attempt to change the order of the attributes within Maya.

**Comment by TrevisanGMW** [comment]
Will track using "Projects"
