### ISSUE TITLE
Prevent installation script from overwriting userSetup.mel

### ISSUE THREAD

**Issue by loonaticx** [TrevisanGMW/gt-tools#77]
(Original issue had a different title, but that wasn't necessarily the problem)
Currently, the auto-installation script will _overwrite_ userSetup.mel located in C:/Users/%username%/maya/20xx/scripts . Because of this, anything that was added within that file isn't registered any more in maya -- a bit of an inconvenience. 

Maybe it would be more feasible if the script were to just append `source "gt_tools_menu.mel"; ` to a new line if the file already exists?

**Comment by TrevisanGMW** [comment]
Hey, sorry for the late reply, for some reason I didn't get a notification for this issue.
Yes, the "setup.bat" should already have this behavior, so I'd assume you're using "setup_mac.sh" or "setup_linux.sh", right?

I haven't had the time to add the code to append it for MAC and LINUX yet, but, yes I'm planning to do that as soon as I can. 👍

**Comment by loonaticx** [comment]
Completely fine! Same here, haha

I ran the batch script using Windows 10.

**Comment by TrevisanGMW** [comment]
Hey @loonaticx,
I have made some changes to the setup.bat (Windows) installer and in my tests it's not overwriting "userSetup.mel" (Inside "maya/20##/scripts")

Try running it again, in case it still replaces it, let me know. 👍

Here is how it behaves on my machine:
1. Before Installation:
![1 before install](https://user-images.githubusercontent.com/12363660/179445176-48576433-021c-450c-baa9-4d609432b50a.jpg)

2. After Installation:
![2 after install](https://user-images.githubusercontent.com/12363660/179445225-839615a8-331c-48a1-877e-501983cfcf90.jpg)

3. After Uninstallation:
![3 after uninstall](https://user-images.githubusercontent.com/12363660/179445244-61328d52-482c-461c-a4d9-0d7c453413b6.jpg)
